name: CI

# Controls when the action will run 
on: 
#Triggers the workflow on the push or pull request events but only for the master branch
  push : 
    branches: [ master ]
  pull_request:
    branches: [ master ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A Workflow run is made up of one or more jobs that can run sequence
jobs:
  # This workflow contatins a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/report/lint-result-debug.html
    
    
  
