name: CI

# Controls when the action will run 
on: 
#Triggers the workflow on the push or pull request events but only for the master branch
  push : 
    branches: [ master ]
  pull_request:
    branches: [ master ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A Workflow run is made up of one or more jobs that can run sequence
jobs:
  # This workflow contatins a single job called "build"
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, World!
      
    - name: Run a multi-line script
      run: |
        echo Add other action to build,
        echo test, and deploy your project.
    
    
  
