# name: CI

# on: 
#   push: 
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#   workflow_dispatch:

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v4

#       - name: Grant execute permission to gradlew
#         run: chmod +x ./gradlew

#       - name: Run Lint
#         run: ./gradlew lintDebug

#       - name: Upload Lint Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: lint-report
#           path: app/build/reports/lint-results-debug.html

#   unit-test:
#     needs: [lint]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code 
#         uses: actions/checkout@v4

#       - name: Grant execute permission to gradlew
#         run: chmod +x ./gradlew

#       - name: Run test
#         run: ./gradlew testDebug --no-build-cache --rerun-tasks

#       - name: Debug Test Reports
#         run: ls -R app/build/reports/tests/

#       - name: Upload the test report
#         uses: actions/upload-artifact@v4
#         with:
#           name: unit-test-report
#           path: app/build/reports/tests/testDebugUnitTest/
          
#   instrumentation-test:
#     needs: [unit-test]
#     runs-on: macos-latest
#     steps:
#       - name: Checkout the Code
#         uses: actions/checkout@v4
        
#       - name: Grant execute permission to gradlew
#         run: chmod +x ./gradlew
        
#       - name: Run Espresso Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 29
#           script: ./gradlew connectedCheck
          
#       - name: Upload Test Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: instrumentation_test_report
#           path: app/build/reports/androidTests/connected/
        
name: CI

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run test
        run: ./gradlew testDebug --no-build-cache --rerun-tasks

      - name: Debug Test Reports
        run: ls -R app/build/reports/tests/

      - name: Upload the test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/
          
  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4
        
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
        
      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk.zip
          unzip android-sdk.zip -d $HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          yes | sdkmanager --update
          yes | sdkmanager --install 'build-tools;35.0.0' platform-tools 'platforms;android-29'
        retry: 3
        
      - name: Run Espresso Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
          
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/
