# name: CI

# on: 
#   push: 
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#   workflow_dispatch:

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v4

#       - name: Grant execute permission to gradlew
#         run: chmod +x ./gradlew

#       - name: Run Lint
#         run: ./gradlew lintDebug

#       - name: Upload Lint Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: lint-report
#           path: app/build/reports/lint-results-debug.html

#   unit-test:
#     needs: [lint]
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code 
#         uses: actions/checkout@v4

#       - name: Grant execute permission to gradlew
#         run: chmod +x ./gradlew

#       - name: Run test
#         run: ./gradlew testDebug --no-build-cache --rerun-tasks

#       - name: Debug Test Reports
#         run: ls -R app/build/reports/tests/

#       - name: Upload the test report
#         uses: actions/upload-artifact@v4
#         with:
#           name: unit-test-report
#           path: app/build/reports/tests/testDebugUnitTest/
          
#   instrumentation-test:
#     needs: [unit-test]
#     runs-on: macos-latest
#     steps:
#       - name: Checkout the Code
#         uses: actions/checkout@v4
        
#       - name: Grant execute permission to gradlew
#         run: chmod +x ./gradlew
        
#       - name: Run Espresso Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: 29
#           script: ./gradlew connectedCheck
          
#       - name: Upload Test Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: instrumentation_test_report
#           path: app/build/reports/androidTests/connected/
        
name: CI

on: 
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run test
        run: ./gradlew testDebug --no-build-cache --rerun-tasks

      - name: Debug Test Reports
        run: ls -R app/build/reports/tests/

      - name: Upload the test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/
          
  build:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4
        
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
        
      - name: Build Debug APK
        run: ./gradlew assembleDebug
        
      - name: Build Release APK
        run: ./gradlew assembleRelease
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk